Repository meshtastic/firmware, pull requests merged in 2025-03, with the labels that each got.

#6187 Switch pio_deps to `native-tft` for flatpak
  .github/workflows/main_matrix.yml
Labels: github_actions

#6241 Small Fix: Don't run Dependabot on protobufs
  .github/dependabot.yml
Labels: github_actions

#6339 meshtasticd: Add MeshToad - USB 1W 'MeshStick'
  bin/config.d/lora-usb-meshtoad-e22.yaml
Labels: linux-native

#6311 Simplify MAX_NUM_NODES, increase limit on large-flash targets.
  arch/nrf52/nrf52.ini
  bin/device-install.bat
  bin/device-install.sh
  src/mesh/mesh-pb-constants.h
  variants/CDEBYTE_E77-MBL/variant.h
  variants/crowpanel-esp32s3-5-epaper/platformio.ini
  variants/diy/platformio.ini
  variants/dreamcatcher/platformio.ini
  variants/esp32-s3-pico/platformio.ini
  variants/heltec_capsule_sensor_v3/platformio.ini
  variants/heltec_v3/platformio.ini
  variants/heltec_vision_master_e213/platformio.ini
  variants/heltec_vision_master_e290/platformio.ini
  variants/heltec_vision_master_t190/platformio.ini
  variants/heltec_wireless_paper/platformio.ini
  variants/heltec_wireless_paper_v1/platformio.ini
  variants/heltec_wireless_tracker/platformio.ini
  variants/heltec_wireless_tracker_V1_0/platformio.ini
  variants/heltec_wsl_v3/platformio.ini
  variants/icarus/platformio.ini
  variants/m5stack_cores3/platformio.ini
  variants/mesh-tab/platformio.ini
  variants/picomputer-s3/platformio.ini
  variants/rak3172/variant.h
  variants/seeed-sensecap-indicator/platformio.ini
  variants/seeed_xiao_s3/platformio.ini
  variants/station-g2/platformio.ini
  variants/t-deck/platformio.ini
  variants/t-eth-elite/platformio.ini
  variants/t-watch-s3/platformio.ini
  variants/tbeam-s3-core/platformio.ini
  variants/tracksenger/platformio.ini
  variants/unphone/platformio.ini
  variants/wio-e5/variant.h
Labels: enhancement

#6352 Support WiFi OTA
  src/mesh/NodeDB.cpp
  src/modules/AdminModule.cpp
  src/platform/esp32/WiFiOTA.cpp
  src/platform/esp32/WiFiOTA.h
  src/platform/esp32/main-esp32.cpp
Labels: requires-docs

#6391 linux-native: allow multiple processes to all bind to the same multicast 2tuple
  arch/portduino/portduino.ini
  src/mesh/udp/UdpMulticastThread.h
Labels: linux-native

#6446 meshtasticd: CH341 / HAT+ Auto Configuration
  bin/config-dist.yaml
  bin/config.d/lora-Adafruit-RFM9x.yaml
  src/platform/portduino/PortduinoGlue.cpp
  src/platform/portduino/PortduinoGlue.h
Labels: linux-native

#6458 meshtasticd: Add FrequencyLabs MeshAdv-Mini Hat
  bin/config.d/lora-MeshAdv-900M30S.yaml
  bin/config.d/lora-MeshAdv-Mini-900M22S.yaml
  src/platform/portduino/PortduinoGlue.h
Labels: linux-native
