Repository meshtastic/firmware, pull requests merged in 2025-08, with the labels that each got.

#7511 128row display
  src/main.cpp
Labels: enhancement, hardware-support, pinned, baseui

#7545 Only toggle screen wake, don't break banners
  src/graphics/Screen.cpp
Labels: baseui, bugfix

#7547 fix: ina226 was not calibrated during init
  src/modules/Telemetry/Sensor/INA226Sensor.cpp
  src/modules/Telemetry/Sensor/INA226Sensor.h
Labels: bugfix

#7558 Rather than mysteriously rebooting, regenerate the keys and inform the user
  src/main.cpp
  src/mesh/NodeDB.cpp
  src/mesh/NodeDB.h
  src/mesh/Router.cpp
  src/modules/AdminModule.cpp
Labels: bugfix

#7502 Initial support for the ThinkNode M5
  src/graphics/EInkDisplay2.cpp
  src/graphics/EInkDisplay2.h
  src/graphics/Screen.cpp
  src/main.cpp
  src/main.h
  src/modules/SerialModule.cpp
  src/platform/esp32/architecture.h
  variants/esp32s3/ELECROW-ThinkNode-M5/pins_arduino.h
  variants/esp32s3/ELECROW-ThinkNode-M5/platformio.ini
  variants/esp32s3/ELECROW-ThinkNode-M5/variant.h
Labels: hardware-support

#7570 Fix a crash on Native reboot
  src/Power.cpp
  src/mesh/api/WiFiServerAPI.cpp
Labels: bugfix

#7604 reorder for correct recognition
  src/platform/nrf52/architecture.h
Labels: high-priority, bugfix

#7596 Stop the bleeding with malicious NodeDB overwrites
  src/modules/NodeInfoModule.cpp
Labels: bugfix

#7589 Mark meshPackets based on which interface received.
  src/mesh/FloodingRouter.cpp
  src/mesh/RadioInterface.cpp
  src/mesh/Router.cpp
  src/mesh/api/PacketAPI.cpp
  src/mesh/udp/UdpMulticastHandler.h
  src/mqtt/MQTT.cpp
Labels: enhancement

#7498 Adding medium and large RU fonts. Fixing RU string width calculation
  src/graphics/ScreenFonts.h
  src/graphics/draw/MessageRenderer.cpp
  src/graphics/fonts/OLEDDisplayFontsRU.cpp
  src/graphics/fonts/OLEDDisplayFontsRU.h
Labels: enhancement

#7612 More spoof remediation
  src/mesh/MeshModule.cpp
  src/mesh/MeshModule.h
  src/mesh/NodeDB.cpp
  src/mesh/Router.cpp
  src/modules/RoutingModule.cpp
  src/modules/RoutingModule.h
Labels: bugfix

#7634 Fix marking LoRa transport mechanism
  src/mesh/RadioInterface.cpp
  src/mesh/Router.cpp
Labels: bugfix

#7641 Thinknode button and backlight fixes
  platformio.ini
  src/graphics/Screen.cpp
  src/graphics/draw/MenuHandler.cpp
  src/input/ButtonThread.cpp
  src/main.cpp
  variants/esp32s3/ELECROW-ThinkNode-M5/variant.h
Labels: bugfix

#7640 Remove JSON serialization from most NRF52 targets
  arch/nrf52/nrf52.ini
  platformio.ini
  variants/nrf52840/rak2560/platformio.ini
  variants/nrf52840/rak4631/platformio.ini
  variants/nrf52840/rak4631_eth_gw/platformio.ini
  variants/nrf52840/rak_wismeshtap/platformio.ini
Labels: enhancement, tech debt

#7655 Add onboard message for devices with screens
  src/graphics/Screen.cpp
  src/graphics/draw/MenuHandler.cpp
  src/graphics/draw/MenuHandler.h
  src/graphics/draw/NotificationRenderer.cpp
Labels: enhancement, baseui

#7652 Don't update the NodeDB if the nodeinfo has a mismatching public key
  src/mesh/NodeDB.cpp
Labels: bugfix

#7636 Support for T-Echo Lite, credits to @Szetya for doing all the heavy lifting!
  src/BluetoothStatus.h
  src/graphics/EInkDisplay2.cpp
  src/main.cpp
  src/modules/SerialModule.cpp
  src/nimble/NimbleBluetooth.cpp
  src/platform/nrf52/architecture.h
  variants/nrf52840/t-echo-lite/platformio.ini
  variants/nrf52840/t-echo-lite/variant.cpp
  variants/nrf52840/t-echo-lite/variant.h
Labels: enhancement, hardware-support

#7660 fix: apply 180 degree hw rotation for Indicator BaseUI
  src/graphics/TFTDisplay.cpp
Labels: bugfix

#7683 Docker: fix web assets location
  Dockerfile
Labels: docker, bugfix

#7681 Only gate PKC behind the simradio CLI flag
  src/mesh/Router.cpp
  src/platform/portduino/PortduinoGlue.cpp
  src/platform/portduino/PortduinoGlue.h
Labels: enhancement

#7676 Add Meshtiny device
  boards/meshtiny.json
  variants/nrf52840/meshtiny/platformio.ini
  variants/nrf52840/meshtiny/variant.cpp
  variants/nrf52840/meshtiny/variant.h
Labels: hardware-support

#7568 Add SDL option to BaseUI on Native
  src/graphics/TFTDisplay.cpp
  src/graphics/TFTDisplay.h
  src/main.cpp
  variants/native/portduino/platformio.ini
Labels: enhancement, baseui

#7722 Pkc fix
  src/mesh/Router.cpp
  src/modules/AdminModule.cpp
Labels: bugfix

#7733 Reduce power of EU433 to 10dBm
  src/mesh/RadioInterface.cpp
Labels: bugfix

#7718 Log more information about ignored packet
  src/mesh/RadioLibInterface.cpp
Labels: enhancement

#7747 Setup ESP32 PM-specific capability flags
  src/platform/esp32/architecture.h
  src/platform/esp32/main-esp32.cpp
  variants/esp32s3/heltec_v3/variant.h
  variants/esp32s3/tbeam-s3-core/variant.h
Labels: enhancement

#7613 T-Lora Pager
  src/detect/ScanI2C.h
  src/detect/ScanI2CTwoWire.cpp
  src/graphics/Screen.cpp
  src/graphics/ScreenFonts.h
  src/graphics/TFTDisplay.cpp
  src/graphics/TFTDisplay.h
  src/graphics/draw/DebugRenderer.cpp
  src/graphics/draw/MenuHandler.cpp
  src/graphics/draw/UIRenderer.cpp
  src/graphics/images.h
  src/input/RotaryEncoderImpl.cpp
  src/input/RotaryEncoderImpl.h
  src/input/TLoraPagerKeyboard.cpp
  src/input/TLoraPagerKeyboard.h
  src/input/cardKbI2cImpl.cpp
  src/main.cpp
  src/main.h
  src/mesh/NodeDB.cpp
  src/modules/Modules.cpp
  src/platform/esp32/architecture.h
  src/platform/extra_variants/t_lora_pager/variant.cpp
  variants/esp32s3/tlora-pager/pins_arduino.h
  variants/esp32s3/tlora-pager/platformio.ini
  variants/esp32s3/tlora-pager/variant.h
Labels: enhancement, hardware-support

#7757 fix: enable device telemetry for elecrow advanced series (MUI)
  variants/esp32s3/elecrow_panel/platformio.ini
Labels: bugfix

#7499 Added HELTEC MeshSolar board.
  boards/heltec_mesh_solar.json
  src/Power.cpp
  src/SerialConsole.cpp
  src/mesh/StreamAPI.cpp
  src/mesh/StreamAPI.h
  src/modules/SerialModule.cpp
  src/platform/nrf52/architecture.h
  src/platform/nrf52/main-nrf52.cpp
  src/power.h
  variants/nrf52840/heltec_mesh_solar/platformio.ini
  variants/nrf52840/heltec_mesh_solar/variant.cpp
  variants/nrf52840/heltec_mesh_solar/variant.h
Labels: enhancement, hardware-support

#7382 BaseUI Show/Hide Frame Functionality
  src/graphics/Screen.cpp
  src/graphics/Screen.h
  src/graphics/draw/DebugRenderer.cpp
  src/graphics/draw/DebugRenderer.h
  src/graphics/draw/MenuHandler.cpp
  src/graphics/draw/MenuHandler.h
  src/graphics/images.h
Labels: enhancement, baseui

#7493 Only send Neighbours if we have some to send.
  src/modules/NeighborInfoModule.cpp
Labels: enhancement

#7772 We don't gotTime if time is 2019.
  src/gps/GPS.cpp
Labels: bugfix

#7762 Add On-Screen Keyboard for UpDown Encoder and Rotary Encoder.
  src/buzz/BuzzerFeedbackThread.cpp
  src/graphics/draw/NotificationRenderer.cpp
  src/input/ButtonThread.h
  src/input/InputBroker.h
  src/input/RotaryEncoderInterruptBase.cpp
  src/input/RotaryEncoderInterruptBase.h
  src/input/RotaryEncoderInterruptImpl1.cpp
  src/input/UpDownInterruptBase.cpp
  src/input/UpDownInterruptBase.h
  src/input/UpDownInterruptImpl1.cpp
Labels: enhancement

#7779 Can't trust RTCs to tell the time.
  src/gps/RTC.cpp
  src/gps/RTC.h
Labels: bugfix

#7789 Change user button to cancel button on Meshtiny
  variants/nrf52840/meshtiny/platformio.ini
  variants/nrf52840/meshtiny/variant.h
Labels: enhancement
