Repository meshtastic/firmware, pull requests merged in 2025-09, with the labels that each got.

#7802 Add support for the RV-3028 on native Linux
  src/configuration.h
  src/gps/RTC.cpp
  src/main.cpp
  variants/native/portduino/platformio.ini
  variants/native/portduino/variant.h
Labels: enhancement, linux-native, bugfix

#7486 Fix device-install.bat baud rate
  bin/device-install.bat
Labels: bugfix

#7816 Fix device-install.bat baud rate (master --> develop)
  .trunk/trunk.yaml
  bin/device-install.bat
Labels: bugfix

#7815 Add GAT562 Mesh Tracker Pro
  boards/gat562_mesh_tracker_pro.json
  variants/nrf52840/gat562_mesh_tracker_pro/platformio.ini
  variants/nrf52840/gat562_mesh_tracker_pro/variant.cpp
  variants/nrf52840/gat562_mesh_tracker_pro/variant.h
Labels: enhancement, hardware-support

#7801 Hold for 20s after GPS lock
  src/gps/GPS.cpp
  src/gps/GPS.h
  variants/nrf52840/tracker-t1000-e/variant.h
  variants/nrf52840/wio-t1000-s/variant.h
Labels: enhancement

#7741 Add RAK WisMesh Tap V2 (ESP32S3) Hardware Variant
  variants/esp32s3/rak_wismesh_tap_v2/pins_arduino.h
  variants/esp32s3/rak_wismesh_tap_v2/platformio.ini
  variants/esp32s3/rak_wismesh_tap_v2/variant.h
Labels: enhancement

#7796 Portduino config refactor
  .clusterfuzzlite/router_fuzzer.cpp
  src/DebugConfiguration.cpp
  src/RedirectablePrint.cpp
  src/gps/GPS.cpp
  src/graphics/Screen.cpp
  src/graphics/TFTDisplay.cpp
  src/graphics/tftSetup.cpp
  src/input/LinuxInput.cpp
  src/input/TouchScreenImpl1.cpp
  src/input/TrackballInterruptBase.h
  src/main.cpp
  src/mesh/LR11x0Interface.cpp
  src/mesh/NodeDB.cpp
  src/mesh/RF95Interface.cpp
  src/mesh/RadioLibInterface.cpp
  src/mesh/Router.cpp
  src/mesh/SX126xInterface.cpp
  src/mesh/SX128xInterface.cpp
  src/mesh/raspihttp/PiWebServer.cpp
  src/modules/Telemetry/HostMetrics.cpp
  src/platform/portduino/PortduinoGlue.cpp
  src/platform/portduino/PortduinoGlue.h
  src/platform/portduino/architecture.h
  variants/native/portduino-buildroot/variant.h
  variants/native/portduino/variant.h
Labels: enhancement, linux-native

#7813 Add RF switch settings for STM32WL variants
  src/mesh/STM32WLE5JCInterface.cpp
  src/mesh/STM32WLE5JCInterface.h
  variants/stm32/CDEBYTE_E77-MBL/platformio.ini
  variants/stm32/CDEBYTE_E77-MBL/rfswitch.h
  variants/stm32/CDEBYTE_E77-MBL/variant.h
  variants/stm32/rak3172/platformio.ini
  variants/stm32/rak3172/rfswitch.h
  variants/stm32/wio-e5/rfswitch.h
Labels: enhancement

#7675 Add TSL2561 sensor
  platformio.ini
  src/detect/ScanI2C.h
  src/detect/ScanI2CTwoWire.cpp
  src/main.cpp
  src/modules/Telemetry/EnvironmentTelemetry.cpp
  src/modules/Telemetry/Sensor/TSL2561Sensor.cpp
  src/modules/Telemetry/Sensor/TSL2561Sensor.h
Labels: enhancement

#7607 Fix INA3221 higher current wrong readings
  platformio.ini
Labels: bugfix

#7844 Enable bmx160 on native
  arch/portduino/portduino.ini
  src/motion/BMX160Sensor.h
  variants/nrf52840/rak4631/platformio.ini
  variants/nrf52840/rak4631_eth_gw/platformio.ini
Labels: enhancement, linux-native

#7752 merge create_test_packet duplicate usage into a shared function
  test/test_meshpacket_serializer/ports/test_encrypted.cpp
  test/test_meshpacket_serializer/test_helpers.h
Labels: enhancement

#7865 Added Last Coordinate counter to Position screen
  src/GPSStatus.h
  src/graphics/draw/UIRenderer.cpp
Labels: enhancement, baseui

#7852 Add a new GPS model CM121.
  src/gps/GPS.cpp
  src/gps/GPS.h
Labels: enhancement

#7869 T-Lora Pager: fix keyboard and improve rotary wheel haptic
  src/input/RotaryEncoderImpl.cpp
  src/sleep.cpp
  variants/esp32s3/tlora-pager/platformio.ini
Labels: bugfix

#7872 Only stop retransmissions when receiving implicit ACK over LoRa
  src/mesh/NextHopRouter.cpp
  src/mesh/ReliableRouter.cpp
  variants/esp32s3/rak_wismesh_tap_v2/variant.h
Labels: bugfix

#7878 Reverting changes made by PR #7520 and adjusting ADC
  variants/nrf52840/heltec_mesh_node_t114/variant.h
Labels: bad config, bugfix

#7859 Upon receiving ACK/reply directly, only update next-hop if we’re the *sole* relayer
  src/mesh/NextHopRouter.cpp
  src/mesh/PacketHistory.cpp
  src/mesh/PacketHistory.h
Labels: bugfix

#7887 Show GPS Date properly in drawCommonHeader
  src/graphics/SharedUIDisplay.cpp
  src/graphics/SharedUIDisplay.h
  src/graphics/draw/ClockRenderer.cpp
  src/graphics/draw/UIRenderer.h
  src/modules/Telemetry/EnvironmentTelemetry.cpp
  src/modules/Telemetry/PowerTelemetry.cpp
Labels: enhancement, baseui, bugfix

#7897 Guard GPS bad time warning logs using GPS_DEBUG
  src/gps/RTC.cpp
Labels: bugfix

#7894 Add BUILD_EPOCH to latest setup step.
  .github/workflows/main_matrix.yml
Labels: bugfix

#7900 chore(deps): update meshtastic/device-ui digest to a04bc94 (#7857)
  platformio.ini
Labels: bugfix

#7904 Only log good times. (It's not always a good time then)
  src/gps/GPS.cpp
Labels: bugfix

#7907 Disable web server on Picomputer so firmware can fit in flash again
  variants/esp32s3/picomputer-s3/platformio.ini
Labels: bugfix

#7870 Use char buffer for probeResponse
  src/gps/GPS.cpp
Labels: enhancement

#7941 Use `sh` in debhelper scripts
  debian/meshtasticd.postinst
  debian/meshtasticd.postrm
Labels: bugfix

#7945 Debian: Correctly generate changelog entries
  debian/changelog
  debian/ci_changelog.sh
Labels: github_actions, bugfix

#7940 PPA: Enable Ubuntu 25.10 (questing)
  .github/workflows/daily_packaging.yml
  .github/workflows/release_channels.yml
Labels: github_actions

#7956 T-Lora Pager: Support LR1121 and SX1280 models
  variants/esp32s3/tlora-pager/rfswitch.h
  variants/esp32s3/tlora-pager/variant.h
Labels: enhancement, hardware-support

#7966 Static memory pool allocation
  src/mesh/MemoryPool.h
  src/mesh/MeshService.cpp
  src/mesh/Router.cpp
  variants/esp32s3/tlora-pager/rfswitch.h
Labels: enhancement

#7974 Add formatting and menu picking for other GPS format options
  src/graphics/draw/MenuHandler.cpp
  src/graphics/draw/MenuHandler.h
  src/graphics/draw/UIRenderer.cpp
  src/graphics/draw/UIRenderer.h
Labels: baseui, bugfix

#7978 Fix json report crashes on esp32
  src/mesh/http/ContentHandler.cpp
Labels: bugfix

#7991 Add c6l BLE and screen support
  src/AmbientLightingThread.h
  src/detect/ScanI2CTwoWire.cpp
  src/graphics/Screen.cpp
  src/graphics/Screen.h
  src/graphics/ScreenFonts.h
  src/graphics/SharedUIDisplay.cpp
  src/graphics/draw/DebugRenderer.cpp
  src/graphics/draw/MenuHandler.cpp
  src/graphics/draw/MenuHandler.h
  src/graphics/draw/MessageRenderer.cpp
  src/graphics/draw/NodeListRenderer.cpp
  src/graphics/draw/NotificationRenderer.cpp
  src/graphics/draw/UIRenderer.cpp
  src/graphics/images.h
  src/graphics/img/icon_small.xbm
  src/input/i2cButton.cpp
  src/input/i2cButton.h
  src/main.cpp
  src/mesh/NodeDB.cpp
  src/mesh/generated/meshtastic/mesh.pb.h
  src/modules/CannedMessageModule.cpp
  src/modules/Modules.cpp
  src/nimble/NimbleBluetooth.cpp
  src/nimble/NimbleBluetooth.h
  src/platform/esp32/architecture.h
  variants/esp32c6/m5stack_unitc6l/pins_arduino.h
  variants/esp32c6/m5stack_unitc6l/platformio.ini
  variants/esp32c6/m5stack_unitc6l/variant.cpp
  variants/esp32c6/m5stack_unitc6l/variant.h
Labels: hardware-support

#8004 When `DEBUG_HEAP` is defined, add free heap bytes to every log line in `RedirectablePrint::log_to_serial`
  platformio.ini
  src/RedirectablePrint.cpp
Labels: enhancement

#8047 C6l fixes
  src/gps/GPS.cpp
  src/nimble/NimbleBluetooth.cpp
  src/nimble/NimbleBluetooth.h
Labels: bugfix

#8052 Make sure to ACK ACKs/replies if next-hop routing is used
  src/mesh/ReliableRouter.cpp
Labels: bugfix

#8046 Fix last build issues on develop
  src/graphics/Screen.cpp
Labels: bugfix

#8055 move HTTP contentTypes to Flash - saves 768 Bytes of RAM
  src/mesh/http/ContentHandler.cpp
Labels: enhancement

#8057 Fix: use `lora.use_preset` config to get name
  src/mesh/Channels.cpp
Labels: bugfix

#8001 Fix Rotary Encoder Button
  src/input/RotaryEncoderInterruptBase.cpp
Labels: bugfix

#7845 add heltec_v4 board.
  boards/heltec_v4.json
  src/mesh/SX126xInterface.cpp
  src/mesh/SX126xInterface.h
  src/platform/esp32/architecture.h
  src/sleep.cpp
  variants/esp32s3/heltec_v4/pins_arduino.h
  variants/esp32s3/heltec_v4/platformio.ini
  variants/esp32s3/heltec_v4/variant.h
Labels: enhancement, hardware-support

#8067 Fix build errors
  src/graphics/images.h
Labels: baseui, bugfix

#8071 Introduce Radio Preset elections through BaseUI
  src/graphics/draw/MenuHandler.cpp
  src/graphics/draw/MenuHandler.h
Labels: enhancement, baseui

#7909 Allow label enforcement job to run on self-hosted runners
  .github/workflows/pr_enforce_labels.yml
Labels: enhancement, github_actions

#8102 Fix 2.4GHz reconfiguration on LR11xx
  src/mesh/LR11x0Interface.cpp
Labels: bugfix

#7992 Feat/0-cost hops for favorite routers
  src/mesh/FloodingRouter.cpp
  src/mesh/NextHopRouter.cpp
  src/mesh/Router.cpp
  src/mesh/Router.h
Labels: enhancement

#5534 If a packet is heard multiple times, rebroadcast using the highest hop limit
  src/mesh/FloodingRouter.cpp
  src/mesh/MeshPacketQueue.cpp
  src/mesh/MeshPacketQueue.h
  src/mesh/MeshService.cpp
  src/mesh/MeshService.h
  src/mesh/NextHopRouter.cpp
  src/mesh/PacketHistory.cpp
  src/mesh/PacketHistory.h
  src/mesh/RadioInterface.h
  src/mesh/RadioLibInterface.cpp
  src/mesh/RadioLibInterface.h
  src/mesh/Router.h
  src/modules/TextMessageModule.cpp
  src/modules/TraceRouteModule.cpp
  src/modules/TraceRouteModule.h
Labels: enhancement, help wanted, pinned

#8053 Make sure next-hop is only set when they received us directly
  src/mesh/FloodingRouter.cpp
  src/mesh/NextHopRouter.cpp
  src/mesh/PacketHistory.cpp
  src/mesh/PacketHistory.h
Labels: bugfix

#8101 reduce cpu load by optimizing OSThread runOnce calls
  arch/esp32/esp32.ini
  platformio.ini
  src/SerialConsole.cpp
  src/SerialConsole.h
  src/buzz/BuzzerFeedbackThread.cpp
  src/buzz/BuzzerFeedbackThread.h
  src/concurrency/OSThread.cpp
  src/input/ButtonThread.cpp
  src/main.cpp
  src/modules/ExternalNotificationModule.cpp
  src/nimble/NimbleBluetooth.cpp
Labels: enhancement

#8111 Correct inverted mute icon
  src/graphics/SharedUIDisplay.cpp
Labels: baseui, bugfix

#8122 BaseUI - Saving GPS Format changes are required
  src/graphics/draw/MenuHandler.cpp
Labels: bug, baseui, bugfix

#8128 Properly output the TCXO Voltage in yaml
  src/platform/portduino/PortduinoGlue.h
Labels: bugfix

#8129 I2S: Fix silent RTTTL regression
  src/AudioThread.h
  src/modules/ExternalNotificationModule.cpp
Labels: bugfix

#8130 Revert cross-preset default-key bridging with UDP and disable UDP by default
  src/mesh/NodeDB.cpp
  src/mesh/Router.cpp
Labels: bugfix

#8144 Finish deprecating the Repeater role behavior
  src/DisplayFormatters.cpp
  src/gps/GPS.cpp
  src/main.cpp
  src/mesh/FloodingRouter.cpp
  src/mesh/FloodingRouter.h
  src/mesh/MeshService.cpp
  src/mesh/NextHopRouter.cpp
  src/mesh/NodeDB.cpp
  src/mesh/RadioInterface.cpp
  src/mesh/Router.cpp
  src/modules/AdminModule.cpp
  src/modules/Modules.cpp
  src/modules/NodeInfoModule.cpp
  src/modules/RoutingModule.cpp
  src/modules/Telemetry/DeviceTelemetry.cpp
  src/modules/Telemetry/HostMetrics.cpp
  src/sleep.cpp
  userPrefs.jsonc
Labels: bugfix

#8148 Bug / Send upgraded (duplicate) packets to phone if the queue removal failed.
  src/mesh/FloodingRouter.cpp
  src/mesh/NextHopRouter.cpp
Labels: bugfix
