Repository meshtastic/firmware, pull requests merged in 2025-04, with the labels that each got.

#6551 Revert "chore(deps): update platformio/toolchain-gccarmnoneeabi to v1.140201.0"
  arch/nrf52/nrf52.ini
Labels: high-priority, dependencies

#5204 Switch to actually maintained thingsboard pubsubclient
  platformio.ini
  src/mqtt/MQTT.cpp
Labels: pinned

#6588 Trunk fixes for heltec mesh pocket.
  boards/heltec_mesh_pocket.json
  src/graphics/EInkDisplay2.cpp
  src/graphics/niche/Drivers/EInk/LCMEN2R13ECC1.cpp
  src/graphics/niche/Drivers/EInk/LCMEN2R13ECC1.h
  variants/heltec_mesh_pocket/nicheGraphics.h
  variants/heltec_mesh_pocket/variant.cpp
  variants/heltec_mesh_pocket/variant.h
Labels: trunk

#6578 FlatHub: bump metainfo.xml on release
  .github/workflows/release_channels.yml
  bin/bump_metainfo/bump_metainfo.py
  bin/bump_metainfo/requirements.txt
  bin/org.meshtastic.meshtasticd.metainfo.xml
  renovate.json
  version.properties
Labels: linux-native

#6632 appdata.xml: Add date to all releases
  bin/org.meshtastic.meshtasticd.metainfo.xml
Labels: linux-native
