Repository meshtastic/firmware, pull requests merged in 2025-07, with the labels that each got.

#7264 Modules and favorite screen fix
  src/graphics/Screen.cpp
Labels: bug

#7247 TFT_MESH Fixes Across Various Devices
  src/graphics/Screen.cpp
  src/graphics/draw/MenuHandler.cpp
Labels: bug

#7240 Key verification flow on BaseUI
  src/graphics/Screen.cpp
  src/graphics/Screen.h
  src/graphics/draw/MenuHandler.cpp
  src/graphics/draw/MenuHandler.h
  src/graphics/draw/NotificationRenderer.cpp
  src/graphics/draw/NotificationRenderer.h
  src/meshUtils.h
  src/modules/CannedMessageModule.cpp
  src/modules/KeyVerificationModule.cpp
  src/modules/KeyVerificationModule.h
  variants/t-deck/variant.h
Labels: enhancement

#7282 Update Screen Wake Default Behavior
  src/graphics/Screen.cpp
  src/graphics/Screen.h
  src/graphics/draw/MenuHandler.cpp
  src/graphics/draw/MenuHandler.h
  src/modules/TextMessageModule.cpp
Labels: baseui

#7332 Actions: Move all Linux packaging into subdir
  .github/workflows/daily_packaging.yml
  .github/workflows/linux_packaging/copr.yml
  .github/workflows/linux_packaging/debian_src.yml
  .github/workflows/linux_packaging/docker_build.yml
  .github/workflows/linux_packaging/docker_manifest.yml
  .github/workflows/linux_packaging/obs.yml
  .github/workflows/linux_packaging/ppa.yml
  .github/workflows/main_matrix.yml
  .github/workflows/release_channels.yml
  .github/workflows/trunk_nightly.yml
  bin/build-firmware.sh
Labels: github_actions

#7379 Actions: Enforce PR labels
  .github/workflows/pr_enforce_labels.yml
  .github/workflows/release_channels.yml
  .github/workflows/update_protobufs.yml
Labels: github_actions

#7342 ESP32c3: Migrate variants to new structure
  variants/diy/platformio.ini
  variants/esp32c3/ai-c3/platformio.ini
  variants/esp32c3/ai-c3/variant.h
  variants/esp32c3/diy/esp32c3_super_mini/pins_arduino.h
  variants/esp32c3/diy/esp32c3_super_mini/platformio.ini
  variants/esp32c3/diy/esp32c3_super_mini/variant.h
  variants/esp32c3/hackerboxes_esp32c3_oled/platformio.ini
  variants/esp32c3/hackerboxes_esp32c3_oled/variant.h
  variants/esp32c3/heltec_esp32c3/pins_arduino.h
  variants/esp32c3/heltec_esp32c3/platformio.ini
  variants/esp32c3/heltec_esp32c3/variant.h
  variants/esp32c3/heltec_hru_3601/pins_arduino.h
  variants/esp32c3/heltec_hru_3601/platformio.ini
  variants/esp32c3/heltec_hru_3601/variant.h
  variants/esp32c3/m5stack-stamp-c3/pins_arduino.h
  variants/esp32c3/m5stack-stamp-c3/platformio.ini
  variants/esp32c3/m5stack-stamp-c3/variant.h
  variants/esp32s2/nugget_s2_lora/platformio.ini
  variants/esp32s2/nugget_s2_lora/variant.h
Labels: github_actions

#7370 Misc cppcheck fixes
  src/buzz/BuzzerFeedbackThread.cpp
  src/graphics/Screen.cpp
  src/graphics/draw/ClockRenderer.cpp
  src/input/ButtonThread.h
  src/mesh/MeshPacketQueue.cpp
  src/mesh/NodeDB.cpp
  src/mesh/NodeDB.h
  src/mesh/PacketHistory.cpp
  src/mesh/PacketHistory.h
  src/modules/CannedMessageModule.cpp
Labels: bugfix

#7345 RP2040/RP2350: Migrate variants to new structure
  variants/rp2040/ec_catsniffer/platformio.ini
  variants/rp2040/ec_catsniffer/variant.cpp
  variants/rp2040/ec_catsniffer/variant.h
  variants/rp2040/feather_rp2040_rfm95/platformio.ini
  variants/rp2040/feather_rp2040_rfm95/variant.h
  variants/rp2040/nibble_rp2040/platformio.ini
  variants/rp2040/nibble_rp2040/variant.h
  variants/rp2040/rak11310/pins_arduino.h
  variants/rp2040/rak11310/platformio.ini
  variants/rp2040/rak11310/variant.h
  variants/rp2040/rp2040-lora/platformio.ini
  variants/rp2040/rp2040-lora/variant.h
  variants/rp2040/rpipico-slowclock/platformio.ini
  variants/rp2040/rpipico-slowclock/variant.h
  variants/rp2040/rpipico/platformio.ini
  variants/rp2040/rpipico/variant.h
  variants/rp2040/rpipicow/platformio.ini
  variants/rp2040/rpipicow/variant.h
  variants/rp2040/senselora_rp2040/pins_arduino.h
  variants/rp2040/senselora_rp2040/platformio.ini
  variants/rp2040/senselora_rp2040/variant.h
  variants/rp2350/rpipico2/platformio.ini
  variants/rp2350/rpipico2/variant.h
  variants/rp2350/rpipico2w/platformio.ini
  variants/rp2350/rpipico2w/variant.h
Labels: github_actions

#7385 UDP for RAK4631 Eth Gw and the t-eth-elite. Solves #7149
  arch/portduino/portduino.ini
  src/mesh/eth/ethClient.cpp
  src/mesh/eth/ethClient.h
  src/mesh/udp/UdpMulticastHandler.h
  src/platform/nrf52/AsyncUDP.cpp
  src/platform/nrf52/AsyncUDP.h
  variants/rak4631_eth_gw/platformio.ini
  variants/t-eth-elite/platformio.ini
Labels: enhancement

#7394 fix UDP builds on nRF
  src/mesh/eth/ethClient.cpp
  src/platform/nrf52/AsyncUDP.cpp
  src/platform/nrf52/AsyncUDP.h
Labels: bugfix

#7393 Unify the shutdown proceedure
  src/Power.cpp
  src/buzz/BuzzerFeedbackThread.cpp
  src/graphics/draw/MenuHandler.cpp
  src/input/ButtonThread.cpp
  src/input/ButtonThread.h
  src/input/ExpressLRSFiveWay.cpp
  src/main.cpp
  src/modules/SystemCommandsModule.cpp
  src/shutdown.h
Labels: bugfix

#7365 Text message rate limiting should return routing error instead
  src/mesh/MeshService.cpp
  src/mesh/MeshService.h
  src/mesh/PhoneAPI.cpp
Labels: enhancement

#7397 ARCH_STM32*WL*
  src/Power.cpp
Labels: bugfix

#7412 Migrate remaining variants to new dir structure
  platformio.ini
  variants/esp32c6/tlora_c6/platformio.ini
  variants/esp32c6/tlora_c6/variant.h
  variants/esp32s3/mesh-tab/pins_arduino.h
  variants/esp32s3/mesh-tab/platformio.ini
  variants/esp32s3/mesh-tab/variant.h
  variants/native/portduino-buildroot/platformio.ini
  variants/native/portduino-buildroot/variant.h
  variants/native/portduino/platformio.ini
  variants/native/portduino/variant.h
Labels: github_actions

#7414 Set canned_message.enabled to true when setting defaults
  src/modules/CannedMessageModule.cpp
Labels: bugfix

#7415 Moves the shutdown thread into the Power class, make shutdown and reboot private
  src/Power.cpp
  src/PowerFSM.cpp
  src/main.cpp
  src/power.h
  src/shutdown.h
Labels: bugfix

#7416 Add a verbose mode flag to meshtasticd
  src/platform/portduino/PortduinoGlue.cpp
Labels: enhancement

#7445 Take control of our PRs!
  .github/workflows/main_matrix.yml
  bin/generate_ci_matrix.py
  variants/esp32/rak11200/platformio.ini
  variants/esp32/tbeam/platformio.ini
  variants/esp32c3/heltec_esp32c3/platformio.ini
  variants/esp32c6/tlora_c6/platformio.ini
  variants/esp32s3/elecrow_panel/platformio.ini
  variants/esp32s3/heltec_v3/platformio.ini
  variants/esp32s3/heltec_vision_master_e213/platformio.ini
  variants/esp32s3/rak3312/platformio.ini
  variants/esp32s3/seeed-sensecap-indicator/platformio.ini
  variants/esp32s3/seeed_xiao_s3/platformio.ini
  variants/esp32s3/station-g2/platformio.ini
  variants/esp32s3/t-deck/platformio.ini
  variants/esp32s3/t-eth-elite/platformio.ini
  variants/nrf52840/heltec_mesh_node_t114/platformio.ini
  variants/nrf52840/rak4631/platformio.ini
  variants/nrf52840/seeed_xiao_nrf52840_kit/platformio.ini
  variants/nrf52840/t-echo/platformio.ini
  variants/nrf52840/tracker-t1000-e/platformio.ini
  variants/rp2040/rak11310/platformio.ini
  variants/rp2040/rpipico/platformio.ini
  variants/rp2040/rpipicow/platformio.ini
  variants/rp2350/rpipico2/platformio.ini
  variants/rp2350/rpipico2w/platformio.ini
  variants/stm32/rak3172/platformio.ini
  variants/stm32/wio-e5/platformio.ini
Labels: github_actions

#7386 Add Trace Route on BaseUI
  src/graphics/draw/MenuHandler.cpp
  src/graphics/draw/MenuHandler.h
  src/modules/TraceRouteModule.cpp
  src/modules/TraceRouteModule.h
Labels: enhancement, baseui

#7455 Fix MHz label
  src/graphics/draw/DebugRenderer.cpp
Labels: bug, baseui, bugfix

#7441 Build RP2350 (Pi Pico 2)
  .github/workflows/main_matrix.yml
  bin/build-firmware.sh
  variants/rp2040/rpipicow/platformio.ini
  variants/rp2350/rpipico2w/platformio.ini
Labels: hardware-support, github_actions

#7450 WashTastic variant
  variants/nrf52840/diy/WashTastic/Platformio.ini
Labels: hardware-support

#7446 Fix MQTT config bugs
  src/mesh/MeshService.h
  src/modules/AdminModule.cpp
  src/mqtt/MQTT.cpp
  test/test_mqtt/MQTT.cpp
Labels: bugfix

#7464 Clear position on GPS deactivation, unless using fixed position
  src/modules/AdminModule.cpp
  src/modules/SystemCommandsModule.cpp
Labels: bugfix

#7470 Validate Serial config console override modes
  src/modules/AdminModule.cpp
  src/modules/SerialModule.cpp
  src/modules/SerialModule.h
  test/test_serial/SerialModule.cpp
Labels: bugfix

#7462 bugfix Add rssi and snr to the store and forward code.
  src/modules/StoreForwardModule.cpp
  src/modules/StoreForwardModule.h
Labels: bugfix

#7489 NodeDB count on MyNodeInfo for client progress reporting
  src/mesh/PhoneAPI.cpp
Labels: enhancement

#7487 Core portnums rebroadcast mode whitelist instead of blacklist
  src/mesh/Router.cpp
Labels: bugfix

#7492 DEBUG_MUTE correctness
  src/mesh/Router.cpp
  src/modules/ReplyModule.cpp
  src/modules/Telemetry/AirQualityTelemetry.cpp
  src/modules/Telemetry/DeviceTelemetry.cpp
  src/modules/Telemetry/EnvironmentTelemetry.cpp
  src/modules/Telemetry/HealthTelemetry.cpp
  src/modules/Telemetry/HostMetrics.cpp
  src/modules/Telemetry/PowerTelemetry.cpp
  src/modules/TextMessageModule.cpp
  src/modules/TraceRouteModule.cpp
  src/modules/WaypointModule.cpp
  src/platform/stm32wl/architecture.h
  src/sleep.cpp
Labels: bugfix

#7506 Heartbeat response
  src/mesh/PhoneAPI.cpp
Labels: enhancement

#7429 Airoha GPS - ignore estimated fixes
  src/gps/GPS.cpp
Labels: bugfix

#7516 Move BLE toggle menu option and add confirmation for canned messages in L1
  src/graphics/draw/MenuHandler.cpp
  src/graphics/draw/MenuHandler.h
  src/modules/CannedMessageModule.cpp
  variants/nrf52840/seeed_wio_tracker_L1/variant.h
Labels: enhancement
