Repository meshtastic/firmware, pull requests merged in 2025-10, with the labels that each got.

#8158 Add DIRECT_MSG_ONLY buzzer mode
  src/buzz/BuzzerFeedbackThread.cpp
  src/graphics/Screen.cpp
  src/graphics/draw/MenuHandler.cpp
  src/modules/ExternalNotificationModule.cpp
Labels: enhancement

#8180 Add support for the manually_verified bool in SharedContact
  src/mesh/NodeDB.cpp
Labels: enhancement

#7986 T-Lora Pager: Fully fix rotary encoder and speaker fuzzing/popping
  src/AudioThread.h
  src/input/InputBroker.cpp
  src/input/InputBroker.h
  src/input/RotaryEncoderImpl.cpp
  src/input/RotaryEncoderImpl.h
  src/main.cpp
  src/platform/nrf52/architecture.h
  src/platform/rp2xx0/architecture.h
  variants/esp32s3/tlora-pager/platformio.ini
Labels: hardware-support

#8185 Add FACTORY_INSTALL option to do a filesystem reset on first boot
  src/mesh/NodeDB.cpp
Labels: enhancement

#8197 Don't use IS_ONE_OF when loading Modules
  src/modules/Modules.cpp
Labels: bugfix

#8205 Calculate airtime of transmitted and received packets separately
  src/mesh/LR11x0Interface.h
  src/mesh/RF95Interface.h
  src/mesh/RadioInterface.cpp
  src/mesh/RadioInterface.h
  src/mesh/RadioLibInterface.cpp
  src/mesh/RadioLibInterface.h
  src/mesh/ReliableRouter.cpp
  src/mesh/SX126xInterface.h
  src/mesh/SX128xInterface.h
  src/platform/portduino/SimRadio.cpp
  src/platform/portduino/SimRadio.h
Labels: enhancement

#8087 Correcting GPS PINs
  variants/nrf52840/t-echo-lite/variant.h
Labels: bugfix

#8216 Reprocess repeated packets and deduplicate logic
  src/mesh/FloodingRouter.cpp
  src/mesh/FloodingRouter.h
  src/mesh/NextHopRouter.cpp
  src/mesh/NextHopRouter.h
  src/mesh/PacketHistory.cpp
Labels: enhancement

#8219 Update next-hops based on traceroute result
  src/modules/TraceRouteModule.cpp
  src/modules/TraceRouteModule.h
Labels: enhancement

#8230 Centralize getNodeId and fix references to owner.id
  src/mesh/NodeDB.cpp
  src/mesh/NodeDB.h
  src/mesh/PhoneAPI.cpp
  src/mesh/wifi/WiFiAPClient.cpp
  src/mqtt/MQTT.cpp
  src/serialization/MeshPacketSerializer.cpp
  src/serialization/MeshPacketSerializer_nRF52.cpp
  test/test_mqtt/MQTT.cpp
Labels: bugfix

#8249 Force coverage tests to run in simulation mode
  variants/native/portduino/platformio.ini
Labels: github_actions, bugfix
