Repository meshtastic/firmware, pull requests merged in 2025-05, with the labels that each got.

#6733 Renovate: Add changelogs for device-ui, cleanup
  arch/esp32/esp32.ini
  arch/esp32/esp32c6.ini
  arch/nrf52/nrf52.ini
  arch/portduino/portduino.ini
  platformio.ini
  renovate.json
Labels: dependencies

#6727 chore(deps): update Bosch BSEC2 to v1.8.2610, BME68x to v1.2.40408
  platformio.ini
  variants/Dongle_nRF52840-pca10059-v1/platformio.ini
  variants/ELECROW-ThinkNode-M1/platformio.ini
  variants/ME25LS01-4Y10TD/platformio.ini
  variants/ME25LS01-4Y10TD_e-ink/platformio.ini
  variants/MS24SF1/platformio.ini
  variants/MakePython_nRF52840_eink/platformio.ini
  variants/MakePython_nRF52840_oled/platformio.ini
  variants/Seeed_Solar_Node/platformio.ini
  variants/canaryone/platformio.ini
  variants/diy/platformio.ini
  variants/ec_catsniffer/platformio.ini
  variants/feather_diy/platformio.ini
  variants/feather_rp2040_rfm95/platformio.ini
  variants/heltec_mesh_node_t114/platformio.ini
  variants/heltec_mesh_pocket/platformio.ini
  variants/meshlink/platformio.ini
  variants/meshlink_eink/platformio.ini
  variants/monteops_hw1/platformio.ini
  variants/nano-g2-ultra/platformio.ini
  variants/nibble_rp2040/platformio.ini
  variants/rak11310/platformio.ini
  variants/rak2560/platformio.ini
  variants/rak4631/platformio.ini
  variants/rak4631_epaper/platformio.ini
  variants/rak4631_epaper_onrxtx/platformio.ini
  variants/rak4631_eth_gw/platformio.ini
  variants/rak_wismeshtap/platformio.ini
  variants/rp2040-lora/platformio.ini
  variants/rpipico-slowclock/platformio.ini
  variants/rpipico/platformio.ini
  variants/rpipico2/platformio.ini
  variants/rpipico2w/platformio.ini
  variants/rpipicow/platformio.ini
  variants/seeed_xiao_nrf52840_kit/platformio.ini
  variants/senselora_rp2040/platformio.ini
  variants/t-echo/platformio.ini
  variants/tlora_c6/platformio.ini
  variants/tracker-t1000-e/platformio.ini
  variants/wio-sdk-wm1110/platformio.ini
  variants/wio-t1000-s/platformio.ini
  variants/wio-tracker-wm1110/platformio.ini
  variants/xiao_ble/platformio.ini
Labels: dependencies

#6776 Actions: Fix end to end tests
  .github/workflows/tests.yml
Labels: github_actions

#6718 Stop the madness! Run as a user (not root)
  .trunk/trunk.yaml
  Dockerfile
  alpine.Dockerfile
  bin/99-meshtasticd-udev.rules
  bin/config-dist.yaml
  bin/meshtasticd.service
  bin/native-install.sh
  debian/control
  debian/meshtasticd.dirs
  debian/meshtasticd.install
  debian/meshtasticd.postinst
  debian/meshtasticd.postrm
  debian/meshtasticd.udev
  meshtasticd.spec.rpkg
  src/mesh/raspihttp/PiWebServer.cpp
Labels: requires-docs, linux-native

#6920 Do position broadcast on secondary channel if disabled on primary
  src/modules/PositionModule.cpp
Labels: requires-docs
